hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls"))
]

hw_project/quotes/urls.py
from django.urls import path
from . import views


app_name = "quotes" 

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root_paginate"),
    path('author/<str:author_id>/',  views.author, name="author_info"),
    path('tag/<str:tag>/',  views.tag_search, name="tag"),
    path('create/author/',  views.create_author, name="create_author"),
    path('create/quote/',  views.create_quote, name="create_quote"),
    path('create/tag/',  views.create_tag, name="create_tag"),
]

hw_project/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
]

hw_project/quotes/models.py
from django.db import models

class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=80)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.fullname}"

class Tag(models.Model):
    name = models.CharField(max_length=40, null=False, unique=True)

    def __str__(self) -> str:
        return f"{self.name}"

class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=False)
    goodreads_page = models.URLField(max_length=200, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    

hw_project/quotes/forms.py
from django import forms
from .models import Quote, Tag, Author

class AuthorForm(forms.ModelForm):
    
    fullname = forms.CharField(max_length=50, required=True, widget=forms.TextInput())
    born_date = forms.CharField(max_length=50, required=False, widget=forms.TextInput())
    born_location = forms.CharField(max_length=80, required=False, widget=forms.TextInput())
    description = forms.CharField(max_length=8000, required=False, widget=forms.TextInput())

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

class TagForm(forms.ModelForm):
    name = forms.CharField(max_length=50, required=True, widget=forms.TextInput())
    class Meta:
        model = Tag
        fields = ['name']

class QuoteForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields["author"].empty_label = "Author not selected"

    quote = forms.CharField(widget=forms.Textarea(attrs={'rows': 10, 'cols' : 60}))
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all().order_by('name'), required=False, widget=forms.SelectMultiple(attrs={'size': 10}))
    author = forms.ModelChoiceField(queryset=Author.objects.all().order_by('fullname'), required=True)
    goodreads_page = forms.URLField(max_length=200, required=False)

    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author', 'goodreads_page']

hw_project/quotes/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from quotes.models import Tag, Quote, Author
from .forms import AuthorForm, QuoteForm, TagForm


def main(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, "quotes/index.html", context={"quotes": quotes_on_page})


def author(request, author_id):
    author_info = Author.objects.get(id=author_id)
    return render(request, "quotes/author.html", context={"author": author_info})


def tag_search(request, tag):
    # select qt.name, qqt.quote_id 
    # from public.quotes_tag qt 
    # join public.quotes_quote_tags qqt on qqt.tag_id = qt.id 
    # join public.quotes_quote qq on qq.id = qqt.quote_id 
    # WHERE qt.name = 'love';

    # --Запрос на поиск цитат за тегом
    tags_search = tag
    quotes_id = Tag.objects.filter(name=tag).values('name', 'quote__id')
    quotes = []
    for item in quotes_id:
        quote = Quote.objects.get(id=item['quote__id'])
        data = Quote.tags.through.objects.filter(quote_id=quote.id).values('tag_id')
        tags = []
        for tag_id in data:
            tag_name = Tag.objects.filter(id=tag_id["tag_id"]).values('name')
            tag_name = list(tag_name.values_list('name', flat=True))
            tags.append(*tag_name)

        quotes.append({"id" : quote.id,
                       "quote" : quote.quote,
                       "tags" : tags,
                       "author" : { "fullname" : quote.author.fullname, "id" : quote.author.id},
                       "goodreads_page" : quote.goodreads_page})  
    return render(request, "quotes/tag_search.html", context={"quotes": quotes, "tags_search": tags_search})


def create_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotes:root")
        else:
            return render(request, "quotes\create_author.html", {'form' : form})
        
    return render(request, "quotes\create_author.html", {'form' : AuthorForm})


def create_quote(request):
    tagss = Tag.objects.all().order_by('name')

    if request.method == "POST":
        form = QuoteForm(request.POST)

        if form.is_valid():
            print(form.cleaned_data['author'])
            print(form.cleaned_data['quote'])
            print(form.cleaned_data['tags'])
            print(form.cleaned_data['goodreads_page'])
            form.save()
            return redirect(to="quotes:root")
        else:

            return render(request, "quotes\create_quote.html", {'form' : form, "tagss" : tagss})
        
    return render(request, "quotes\create_quote.html", {'form' : QuoteForm, "tagss" : tagss})


def create_tag(request):
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotes:root")
        else:
            return render(request, "quotes\create_tag.html", {'form' : form})
        
    return render(request, "quotes\create_tag.html", {'form' : TagForm})

hw_project/quotes/templates/quotes/author.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="author-details">
<h3 class="author-title">{{author.fullname}}</h3>
<p><strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span> <span class="author-born-location">{{author.born_location}}</span></p>
<p><strong>Description:</strong></p>
<div class="author-description">
    {{author.description}}
</div>

{% endblock %}

hw_project/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" 
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet", href="{% static 'quotes/style.css' %}">
    <title>Homework</title>   
</head> 
<body>
    <div class="container">
        <div class="row header-box pt-3">
            <div class="col-md-8 mb-4">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    {% if user.is_authenticated %} 
                    <a href="{% url 'quotes:create_quote' %}" class="btn btn-primary">Create quote</a>
                    <a href="{% url 'quotes:create_tag' %}" class="btn btn-primary">Create tag</a>
                    <a href="{% url 'quotes:create_author' %}" class="btn btn-primary">Create author</a>

                    <a href="{% url 'users:logout' %}" class="btn btn-outline-danger">Logout</a>
                    {% else %}
                    <a href="{% url 'users:signup' %}" class="btn btn-outline-success">SignUP</a>
                    <a href="{% url 'users:login' %}" class="btn btn-outline-success">Login</a>
                    {% endif %}
                </p>
            </div>
        </div>
    
{% block content %} {% endblock %}



</div>
</body>
</html>

hw_project/quotes/templates/quotes/create_author.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<h1> Create Author </h1>

<form method="post" action="{% url 'quotes:create_author' %}">
    {% csrf_token %}
    <div style="padding: 10px;">
        <div class="col-md-4">
            <label class="form-group">Author fullname:</label>
            {{ form.fullname }}
        </div>
        <div class="col-md-4">
            <label class="form-group">Author born date:</label>
            {{ form.born_date }}
        </div>
        
        <div class="col-md-4">
            <label class="form-group">Author born location:</label>
            {{ form.born_location }}
        </div>
        
        <div class="col-md-4">
            <label class="form-group">Author description:</label>
            {{ form.description }}
        </div>

        <span>{{ form.errors.fullname }}</span>
        <span>{{ form.errors.born_date }}</span>
        <span>{{ form.errors.born_location }}</span>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="col-md-4">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-primary">Reset</button>
    </div>
</form>


{% endblock %}

hw_project/quotes/templates/quotes/create_quote.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
<h1> Create Quote </h1>

<form method="post" action="{% url 'quotes:create_quote' %}">
    {% csrf_token %}
    <div style="padding: 10px;">
        <div class="col-md-4">
            <label class="form-group">Author:</label>
            {{ form.author }}
        </div>
        <span>{{ form.errors.author }}</span>

        <div class="col-md-4">
            <label class="form-group">Author quote:</label>
            {{ form.quote }}
        </div>
        <span>{{ form.errors.quote }}</span>
        
        <div class="col-md-4">
            <label class="form-group">Open this select menu tags:</label>
            {{form.tags}}
            <span>{{ form.errors.tags }}</span>
        </div>  
        
        <div class="col-md-4">
            <label class="form-group">Author goodreads:</label>
            {{ form.goodreads_page }}
        </div>
        <span>{{ form.errors.goodreads_page }}</span>

    </div>
    <div class="col-md-4">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-primary">Reset</button>
    </div>
</form>


{% endblock %}

hw_project/quotes/templates/quotes/create_tag.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
<h1> Create Tag </h1>

<form method="post" action="{% url 'quotes:create_tag' %}">
    {% csrf_token %}
    <div style="padding: 10px;">
        <div class="col-md-4">
            <label class="form-group">Name tag:</label>
            {{ form.name }}
        </div>

        <span>{{ form.errors.tag }}</span>
    </div>
    <div class="col-md-4">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-primary">Reset</button>
    </div>
</form>


{% endblock %}

hw_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.quote}}</span>
            <span>by <small class="author" itemprop="author">{{quote.author.id|author}}</small>
        <a href="/author/{{quote.author.id}}">(about)</a>
        
        {% if user.is_authenticated %}
            {% if quote.goodreads_page %}
            <a href="{{quote.goodreads_page}}">Goodreads page</a>
            {% endif %}
        {% endif %}
        
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags.all %}
            <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
            {% endfor %}
            
        </div>
    </div>
    {% endfor %}
    <nav>
        <ul class="pager">
            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}" 
                href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                <span aria-hidden="true">←</span> Previous</a>
            </li> 
            
            <li class="next">
                <a class="{% if not quotes.has_next %} disabled {% endif %}" 
                href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                Next <span aria-hidden="true">→</span></a>
            </li>
            
        </ul>
    </nav>
    </div>
   <div class="col-md-4 tags-box">
            <h2>Top Ten tags</h2>
            {% for tag in quotes.quote.tags|tags %}
            <span class="tag-item">
            <a class="tag" style="font-size: 28px" href="/tag/{{ tag.name }}/">{{tag.name}}</a>
            </span>       
            {% endfor %}
    </div>
</div>

{% endblock %}

hw_project/quotes/templates/quotes/tag_search.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}



<div class="row">
    <div class="col-md-8">
        <h3>Viewing tag: <a href="/tag/{{tags_search}}">{{tags_search}}</a></h3>
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.quote}}</span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="/author/{{quote.author.id}}">(about)</a>
        
        {% if user.is_authenticated %}
        <a href="{{quote.goodreads_page}}">Goodreads page</a>
        {% endif %}
        
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags %}
            <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
            {% endfor %}
            
        </div>
    </div>
    {% endfor %}
    <nav>
        <ul class="pager">
            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}" 
                href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                <span aria-hidden="true">←</span> Previous</a>
            </li> 
            
            <li class="next">
                <a class="{% if not quotes.has_next %} disabled {% endif %}" 
                href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                Next <span aria-hidden="true">→</span></a>
            </li>
            
        </ul>
    </nav>
    </div>
   <div class="col-md-4 tags-box">
            <h2>Top Ten tags</h2>
            {% for tag in quotes.quote.tags|tags %}
            <span class="tag-item">
            <a class="tag" style="font-size: 28px" href="/tag/{{ tag.name }}/">{{tag.name}}</a>
            </span>       
            {% endfor %}
    </div>
</div>

{% endblock %}